### ISSUE TITLE
AnonymizedYears doesn't work & Display issues

### ISSUE THREAD

**Issue by genmielec** [drifted-in/genopro-webapp-exporter#2]
I don't see living people

I can't use the anonymizedYears parameter

when typing -anonymizedYears: -1 crashes error, when I type -anonymizedYear-1 it doesn't throw the error but people still can't see it.

I do not assume a new thread, because maybe anonymisation gives such an effect?
https://i.imgur.com/D8tv04Y.png

1) Dates are obscured by "person graphics".
2) Not all lines can be seen
3) I can't see everyone in the tree

My tree:
https://cutt.ly/Wt9XRux

**Comment by jan-tosovsky-cz** [comment]
The expected form is -anonymizedYears:-1 (i.e. no space after colon).

**Comment by genmielec** [comment]
Error:

> D:\>java -jar D:\genopro-webapp-exporter.jar -in:"D:\family-tree.gno" -out:"D:\family-tree" -mode:static -anonymizedYears:-1
> Exception in thread "main" java.lang.NullPointerException
>         at sun.font.FontDesignMetrics.stringWidth(Unknown Source)
>         at in.drifted.tools.genopro.webapp.SvgRenderer.renderIndividualDates(SvgRenderer.java:537)
>         at in.drifted.tools.genopro.webapp.SvgRenderer.renderIndividual(SvgRenderer.java:486)
>         at in.drifted.tools.genopro.webapp.SvgRenderer.render(SvgRenderer.java:83)
>         at in.drifted.tools.genopro.webapp.WebAppExporter.generateMainHtml(WebAppExporter.java:111)
>         at in.drifted.tools.genopro.webapp.WebAppExporter.exportAsStaticPage(WebAppExporter.java:71)
>         at in.drifted.tools.genopro.webapp.App.main(App.java:138)

**Comment by jan-tosovsky-cz** [comment]
For displaying dates I use two lines option (menu Display | Date of Birth and Date of Death (on separate lines)) and this way is apparently hardcoded to my code as well. Now it makes sense why the second line is always covered with the gender symbol. However, it should not crash.

**Comment by genmielec** [comment]
That's right I improved the view on two lines and now it's good ... It's not what I wanted, but it can be :)
https://cutt.ly/Wt9XRux

But the problem with anonymized is still unsolved .. start a new thread?

**Comment by jan-tosovsky-cz** [comment]
I've changed my mind and now dedicating this issue back to that original anonymization issue. For label position issue I've filled a separate enhancement https://github.com/drifted-in/genopro-webapp-exporter/issues/3. 

After testing your file I was able to find the root cause. That exception is thrown in cases individual has no birth date specified, but birthplace.

It has just been fixed. Please try newly updated app.zip.

**Comment by genmielec** [comment]
I used app.zip from the date 4/20/2016 (23:30).
Still the same
https://cutt.ly/Ot8katB

Doesn't show people without a place of birth and living people.
Now when generating the page doesn't throw any errors.

My GNO file:
https://cutt.ly/Ct8kja0

**Comment by jan-tosovsky-cz** [comment]
I am getting different (correct) output using above commands. Please check you use latest jar file.
